name: Pull Request

on:
  workflow_call:
    inputs:
      python-version-unit:
        required: false
        description: "Python version"
        type: string
        default: "['3.8', '3.10']"
      python-version-func:
        required: false
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: "Tox version, which should be used, e.g. `<4`"
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      posargs:
        required: false
        description: |
          "Optional postargs for `tox -e func -- <postargs>`, e.g. '--series jammy'"
        type: string
        default: "['--series jammy']"
      # actions-operator
      provider:
        required: false
        type: string
        default: "lxd"

concurrency:
  group: charm-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    name: Charm PR
    uses: ./.github/workflows/_pull-request.yaml
    secrets: inherit
    with:
      python-version-unit: ${{ inputs.python-version-unit }}
      python-version-func: ${{ inputs.python-version-func }}
      tox-version: ${{ inputs.tox-version }}
      working-directory: ${{ inputs.working-directory }}
      snapcraft: false
      juju-env: true
      provider: ${{ inputs.provider }}
