name: Pull Request

on:
  workflow_call:
    inputs:
      python-version-unit:
        required: false
        description: "Python version"
        type: string
        default: "['3.8', '3.10']"
      python-version-func:
        required: false
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: "Tox version, which should be used, e.g. `<4`"
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      posargs:
        required: false
        description: |
          "Optional postargs for `tox -e func -- <postargs>`, e.g. '--series jammy'"
        type: string
        default: "['']"  # empty string as default so func test is run at least one
      # actions-operator
      juju-env:
        required: false
        type: boolean
        default: false
      provider:
        required: false
        type: string
        default: "lxd"

concurrency:
  group: snap-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snap:
    name: Snap PR
    uses: ./.github/workflows/_pull-request.yaml
    secrets: inherit
    with:
      python-version-unit: ${{ inputs.python-version-unit }}
      python-version-func: ${{ inputs.python-version-func }}
      tox-version: ${{ inputs.tox-version }}
      working-directory: ${{ inputs.working-directory }}
      snapcraft: true
      juju-env: ${{ inputs.juju-env }}
      provider: ${{ inputs.provider }}

