on:
  workflow_call:
    inputs:
      channel:
        description: |
          A comma-separated list of channels, to which the snap should be released, in
          string format. By default, the snap will be released to the "latest/edge" channel.
          Examples:
          - "latest/edge"
          - "latest/edge,latest/candidate,2.9/edge"
        required: false
        type: string
        default: latest/edge

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for proper versioning
      - uses: snapcore/action-build@v1
        id: build
      - name: Upload locally built Snap artifact
        uses: actions/upload-artifact@v3
        with:
          name: snap-artifact
          path: ${{ steps.build.outputs.snap }}

  publish:
    name: Publish Snap
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: snap-artifact
      - id: get-snap-name
        run: echo "SNAP_FILE=$(ls *.snap)" >> $GITHUB_OUTPUT
      - name: Release snap to the specified channel
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.get-snap-name.outputs.SNAP_FILE }}
          release: ${{ inputs.channel }}
