on:
  workflow_call:
    inputs:
      channel:
        description: |
          A comma-separated list of channels, to which the snap should be released, in
          string format. By default, the snap will be released to the "latest/edge" channel.
          Examples:
          - "latest/edge"
          - "latest/edge,latest/candidate,2.9/edge"
        required: false
        type: string
        default: latest/edge
      python-version-unit:
        required: true
        description: "Python version"
        type: string
        default: "['3.8', '3.10']"
      python-version-func:
        required: true
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: |
          Tox version, which should be used, e.g. `<4`. If not specified, the
          latest version of tox will be installed.
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      snapcraft:
        required: false
        description: |
          Flag if snap is tested. If set to true, snapcraft will be installed.
        type: boolean
        default: true
      commands:
        required: true
        description: |
          Command to run functional tests in strategies. It accepts a stringified list
          of commands, which allows you to run multiple tests with different parameters.
          This is a required input field.
          Examples:
          - "['make functional']"
          - "['FUNC_ARGS="--series jammy" make functional',
             'FUNC_ARGS="--series focal" make functional']"
          - "['tox -e func -- -sv --series jammy', 'tox -e func -- -sv --series focal']"
        type: string
      timeout-minutes:
        required: false
        description: "Configurable timeout limit for functional tests job"
        type: number
        default: 60
      # actions-operator
      provider:
        required: false
        type: string
        default: "lxd"
      nested-containers:
        required: false
        type: boolean
        default: false

jobs:
  lint-unit:
    uses: ./.github/workflows/_lint-unit.yaml
    secrets: inherit
    with:
      python-version: ${{ inputs.python-version-unit }}
      tox-version: ${{ inputs.tox-version }}
      working-directory: ${{ inputs.working-directory }}

  func:
    uses: ./.github/workflows/_func.yaml
    needs: lint-unit
    secrets: inherit
    with:
      python-version: ${{ inputs.python-version-func }}
      tox-version: ${{ inputs.tox-version }}
      working-directory: ${{ inputs.working-directory }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
      snapcraft: ${{ inputs.snapcraft }}
      commands: ${{ inputs.commands }}
      provider: ${{ inputs.provider }}
      nested-containers: ${{ inputs.nested-containers }}

  build:
    uses: ./.github/workflows/_snap-build.yaml
    needs: func
    secrets: inherit
  
  release-snap:
    uses: ./.github/workflows/_snap-release.yaml
    needs: build
    secrets: inherit
    with:
      channel: ${{ inputs.channel }}
