name: Test for func workflow

on:
  push:
    branches: [v2]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [v2]

jobs:
  charm-func:
    uses: ./.github/workflows/func.yaml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: "make functional"
            juju-channel: "2.9/stable"
          - command: "make functional31"
            juju-channel: "3.1/stable"
    with:
      nested-containers: true
      timeout-minutes: 120
      working-directory: ./tests/test_charm_repo

  snap-func:
    uses: ./.github/workflows/func.yaml
    secrets: inherit
    with:
      snapcraft: true
      working-directory: ./tests/test_snap_repo
