name: Tests for lint-unit workflow

on:
  push:
    branches: [v2]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [v2]

jobs:
  charm-lint-unit:
    uses: ./.github/workflows/lint-unit.yaml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.10']
    with:
      working-directory: ./tests/test_charm_repo

  snap-lint-unit:
    uses: ./.github/workflows/lint-unit.yaml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.10']
    with:
      working-directory: ./tests/test_snap_repo
