name: Test for PR workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
  pull_request_review:
    types: [ submitted ]

jobs:
  charm-pr:
    uses: ./.github/workflows/charm-pull-request.yaml
    secrets: inherit
    with:
      python-version-unit: "['3.10']"
      python-version-func: "3.10"
      tox-version: "<4"
      working-directory: ./tests/test_charm_repo
      posargs: "['--series jammy']"

  snap-pr:
    uses: ./.github/workflows/snap-pull-request.yaml
    secrets: inherit
    with:
      python-version-unit: "['3.10']"
      python-version-func: "3.10"
      tox-version: "<4"
      working-directory: ./tests/test_snap_repo
